### ISSUE TITLE
Health Checker - New IIS Section

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#1363]
**Describe The Request**
There are a lot of things with IIS that we want to display and know about other than just the Web App Pools. There are a few issues that have been wanting to do some extra things, so let's display the information in a clear-cut chart.

**Work Items this issue should address**
- [x] #1353 - Always get the correct web.config path with `Get-WebConfigFile`
- [x] #1343 - IIS URL Rewrite Rules - with inheritance logic breakdown
- [x] #1131 - Validate Virtual Directory Path for default sites
- [x] #1094 - Making sure IIS Web Site is started - throw error if not
- [x] #955 - Display Thumbprint of bound Certificate(s)
- [x] A 3rd Site with OWA/ECP = https://techcommunity.microsoft.com/t5/exchange-team-blog/configuring-multiple-owa-ecp-virtual-directories-on-the-exchange/ba-p/611217
- [x] Display issue with converting to XML for `applicationHost.config` or for `web.config` files

**Additional context**

Here is a mockup of what the table should look like:

```
IIS Information

    Web Sites
            Name              Running       Protocol - Bindings - Certificate
            ----              -------       ---------------------------------
            Default Web Site  Started       http 127.0.0.1:80    Thumbprint
            Exchange Back End Started       http 127.0.0.1:80    Thumbprint

    Web App Pool
        AppPoolName                          State    GCServerEnabled  RestartConditionSet
        -----------                          -----    ---------------  -------------------
        MSExchangeMapiFrontEndAppPool        Started  False            False
        MSExchangeOWAAppPool                 Started  False            False
        MSExchangeECPAppPool                 Started  False            False
        MSExchangeRestAppPool                Started  False            False
        MSExchangeMapiAddressBookAppPool     Started  False            False
        MSExchangeRpcProxyFrontEndAppPool    Started  False            False
        MSExchangePowerShellAppPool          Started  False            False
        MSExchangePowerShellFrontEndAppPool  Started  False            False
        MSExchangeRestFrontEndAppPool        Started  False            False
        MSExchangeMapiMailboxAppPool         Started  False            False
        MSExchangeOABAppPool                 Started  False            False
        MSExchangePushNotificationsAppPool   Started  False            False
        MSExchangeOWACalendarAppPool         Started  False            False
        MSExchangeAutodiscoverAppPool        Started  False            False
        MSExchangeServicesAppPool            Started  False            False
        MSExchangeSyncAppPool                Started  True             False
        MSExchangeRpcProxyAppPool            Started  False            False

    
    Virtual Directories 
        Name                   ExtendedProtection   RequireSSL     URLRewriteRule   IPFilterEnabled  Authentication(with Providers)
        ----                   ------------------   ----------     --------------   ---------------  ------------------------------
        Default Web Site\API    True                True (128-bit) RuleName Action   True            Anonymous Auth
                                                                                                     Windows (Kerb, NLTM)
        Exchange Back End\API   True                True (128-bit) RuleName Action   False           Windows (Kerb)
        ...
        
```

**Comment by dpaulson45** [comment]
Went through and created a 3rd owa/ecp web site. This does show up in the IIS Information section already. It doesn't show up in our EP test, but this is to be expected at this time.



![Image](https://github.com/microsoft/CSS-Exchange/assets/22776718/b8f2263e-53d7-4602-a47c-1c0021208a8f)



![Image](https://github.com/microsoft/CSS-Exchange/assets/22776718/1840673f-0d78-4e5c-aa67-4a9165e0b628)


Because this is already there and working, going to close out this issue as everything else has been completed.
