### ISSUE TITLE
[Work Item] Exchange Log Collector Update

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/CSS-Exchange#1836]
**Describe the work**
Update Exchange Log Collector to collect additional logs that we are currently missing. 

**Additional Context**

```[tasklist]
### Tasks
- [ ] Throttling Delivery #1790 
- [ ] Pipeline Tracing Data #1769 
- [ ] Database Path Information #1138 
- [ ] applicationHost.config file #1064 
- [ ] App Pool IDs #1063 
- [ ] `Get-RemoteDomain`, `Get-AcceptedDomain`, and `Get-TransportRule` #1050 
```
