### ISSUE TITLE
[Issue] - Health Checker TokenCacheModule check doesn't work as expected on WS < 2016

### ISSUE THREAD

**Issue by lusassl-msft** [microsoft/CSS-Exchange#1854]
**Describe the issue**
The `TokenCacheModule` check doesn't work properly when executed against OS that are older than Windows Server 2016 (for example, Windows Server 2012 R2). This causes false-positives and leads to questions from customers who are using the script to validate that the TokenCacheModule was successfully added back post October 2023 SU installation.

**Expected behavior**
The check should return a valid result regardless if it was executed against a legacy OS or not.

**Additional context**
The root cause is that the TokenCacheModule IIS state will never returned on legacy OS. This is caused by the module skip list that we use within the `Get-IISModules` function to skip system modules that were not signed by Microsoft on OS older Windows Server 2016. We need to adjust the `Get-IISModules` function to return the IIS load state for each module and on each OS regardless if signed or not or on the skip list. 

```[tasklist]
### Tasks
- [x] Improve the Get-IISModules function to return all modules that are loaded
- [x] Adjust the "IIS module anomalies detected" output for any module that was skipped due to SkipLegacyOSModulesCheck $true
- [x] Update and add a unit test to make sure that the function returns all modules as we expect to be
```
